server:
  port: 8180

spring:
  application:
    name: nacos-rabbitmq
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"