server:
  port: 8180

spring:
  application:
    name: nacos-rabbitmq
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    #新版本使用这个即可 confirm模式
    publisher-confirm-type: correlated
    #老版本的话用下面这个即可开启confirm确认模式
    #publisher-confirms: true
    #开启确认模式
    publisher-returns: true
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"