server:
  port: 8308

spring:
  application:
    name: nacos-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    loadbalancer:
      ribbon:
        enabled: false
    sentinel:
      transport:
        port: 8719 #指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer，默认值为8719
        dashboard: localhost:8090  #启动本项目后需要请求一次才能向sentinel控制台注册
      datasource:
        ds2:
          nacos:
            server-addr: localhost:8848
            data-id: sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"

service-url:
  nacos-user-service: http://nacos-user-service